import {promises as fs} from "node:fs";
import path from "node:path";
import os from "node:os";
import {execFile} from "node:child_process";
import {promisify} from "node:util";
const execFileAsync=promisify(execFile);
export type SandboxResult={available:boolean;status:"PASSED"|"FAILED"|"SKIPPED";stdout:string;stderr:string;reason?:string};
function validatePackageJson(raw:string){const pkg=JSON.parse(raw);if(pkg.scripts){const allowed=new Set(["build","test","lint"]);for(const [name,value] of Object.entries(pkg.scripts)){if(!allowed.has(name))throw new Error(`Sandbox refused package script: ${name}`);if(typeof value!=="string")throw new Error(`Invalid script: ${name}`);}}return pkg;}
async function docker(args:string[],timeout=180000){return execFileAsync("docker",args,{timeout,maxBuffer:2*1024*1024});}
export async function runSandbox(files:Array<{path:string;content:string}>):Promise<SandboxResult>{try{await execFileAsync("docker",["--version"],{timeout:3000});}catch{return{available:false,status:"SKIPPED",stdout:"",stderr:"",reason:"Docker is not available. No host command was executed."};}const workspace=await fs.mkdtemp(path.join(os.tmpdir(),"lumia-sandbox-"));try{for(const file of files){if(!file.path||file.path.startsWith("/")||file.path.includes("..")||file.path.includes("\\"))throw new Error(`Unsafe generated path: ${file.path}`);const target=path.join(workspace,file.path);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,file.content,"utf8");}let hasPackage=false;try{validatePackageJson(await fs.readFile(path.join(workspace,"package.json"),"utf8"));hasPackage=true;}catch(e){if((e as NodeJS.ErrnoException).code!=="ENOENT")throw e;}if(!hasPackage)return{available:true,status:"SKIPPED",stdout:"",stderr:"",reason:"No package.json was generated."};
const installArgs=["run","--rm","--cpus","1","--memory","768m","--pids-limit","128","--read-only","--tmpfs","/tmp:rw,noexec,nosuid,size=128m","--tmpfs","/root/.npm:rw,nosuid,size=256m","-v",`${workspace}:/workspace:rw","node:22-alpine","sh","-lc","cd /workspace && npm install --ignore-scripts --no-audit --no-fund"];
try{await docker(installArgs,180000);}catch(e:any){return{available:true,status:"FAILED",stdout:e?.stdout||"",stderr:e?.stderr||String(e?.message||e),reason:"Dependency installation failed."};}
const buildArgs=["run","--rm","--network","none","--cpus","1","--memory","768m","--pids-limit","128","--read-only","--tmpfs","/tmp:rw,noexec,nosuid,size=128m","-v",`${workspace}:/workspace:ro","node:22-alpine","sh","-lc","cd /workspace && npm run build"];
try{const r=await docker(buildArgs,180000);return{available:true,status:"PASSED",stdout:r.stdout,stderr:r.stderr};}catch(e:any){return{available:true,status:"FAILED",stdout:e?.stdout||"",stderr:e?.stderr||String(e?.message||e)};}}catch(e){return{available:true,status:"FAILED",stdout:"",stderr:e instanceof Error?e.message:"Sandbox setup failed."};}finally{await fs.rm(workspace,{recursive:true,force:true}).catch(()=>{});}}
