"use client";
import {useEffect,useState} from "react";
type User={id:string;email:string;name:string|null}; type Project={id:string;name:string;status:string;_count?:{files:number}};
export default function Builder(){const[p,setP]=useState("");const[s,setS]=useState("Checking session…");const[r,setR]=useState<any>(null);const[user,setUser]=useState<User|null>(null);const[projects,setProjects]=useState<Project[]>([]);const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[name,setName]=useState("");const[mode,setMode]=useState<"signin"|"signup">("signin");const[selected,setSelected]=useState("");
async function load(){const me=await fetch("/api/auth/me").then(x=>x.json());setUser(me.user);if(me.user){const x=await fetch("/api/projects").then(v=>v.json());setProjects(x.projects||[]);setS("Ready") }else setS("Sign in to start building")}
useEffect(()=>{load()},[]);
async function auth(){setS(mode==="signin"?"Signing in…":"Creating account…");const url=mode==="signin"?"/api/auth/signin":"/api/auth/signup";const body=mode==="signin"?{email,password}:{email,password,name};const x=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await x.json();if(!x.ok)throw Error(d.error||"Authentication failed");setUser(d.user);setS("Ready");setEmail("");setPassword("");const list=await fetch("/api/projects").then(v=>v.json());setProjects(list.projects||[])}
async function build(){setS("Building with NVIDIA…");try{const x=await fetch("/api/builder/build",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:p,projectId:selected||undefined})});const d=await x.json();if(!x.ok||!d.ok)throw Error(d.error||"Build failed");setR(d);setSelected(d.projectId);setS(d.result?.status==="PASSED"?`Build passed after ${d.retries} debug retry(s)`:d.result?.status||"Done");const list=await fetch("/api/projects").then(v=>v.json());setProjects(list.projects||[])}catch(e){setS(e instanceof Error?e.message:"Failed")}}
async function signout(){await fetch("/api/auth/signout",{method:"POST"});setUser(null);setProjects([]);setS("Sign in to start building")}
if(!user)return <main style={{maxWidth:560,margin:"60px auto",padding:24,fontFamily:"Arial"}}><h1>LUMIA AI BUILDER</h1><p>{mode==="signin"?"Sign in to your workspace":"Create your Lumia account"}</p>{mode==="signup"&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Name" style={{width:"100%",padding:12,marginBottom:10}}/>}<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" type="email" style={{width:"100%",padding:12,marginBottom:10}}/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (8+ characters)" type="password" style={{width:"100%",padding:12}}/><button onClick={()=>auth().catch(e=>setS(e.message))} style={{marginTop:12,padding:12,width:"100%"}}>{mode==="signin"?"Sign in":"Sign up"}</button><button onClick={()=>setMode(mode==="signin"?"signup":"signin")} style={{marginTop:8,padding:10,width:"100%"}}>{mode==="signin"?"Create an account":"I already have an account"}</button><p>{s}</p></main>;
return <main style={{maxWidth:1100,margin:"40px auto",padding:20,fontFamily:"Arial"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h1>LUMIA AI BUILDER</h1><p>Plan → Code → Docker Sandbox → Debug/Retry → Save</p></div><button onClick={signout}>Sign out</button></header><label>Saved project</label><select value={selected} onChange={e=>setSelected(e.target.value)} style={{display:"block",width:"100%",padding:10,margin:"8px 0 16px"}}><option value="">Create new project on build</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name} — {x.status}</option>)}</select><textarea value={p} onChange={e=>setP(e.target.value)} placeholder="Describe the app you want Lumia to build" style={{width:"100%",minHeight:160,padding:12}}/><button onClick={build} disabled={!p.trim()} style={{marginTop:12,padding:12}}>Build with Lumia</button><p>{s}</p>{r&&<><h2>{r.plan?.summary}</h2><h3>Generated files ({r.files?.length||0})</h3><ul>{r.files?.map((f:any,i:number)=><li key={i}>{f.path}</li>)}</ul><h3>Debug attempts</h3><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(r.attempts,null,2)}</pre></>}</main>}
